# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY seamless_communication /app/seamless_communication
COPY seamless_expressive_pts /app/seamless_expressive_pts

RUN apt-get update && apt-get install -y libsndfile1 build-essential ffmpeg && rm -rf /var/lib/apt/lists/*
RUN cd seamless_communication && pip install .

COPY http_seamless.py /app
# Make port 8080 available to the world outside this container
# (Cloud Run will map its external port to this one via the PORT env var)
EXPOSE 8080

# Define environment variable
ENV PYTHONUNBUFFERED=1

# Run http_seamless.py when the container launches
CMD ["python", "http_seamless.py"]
