name: Deploy to GitHub Pages

on:
  push:
    branches:
      - web

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./BlindWiki2
        run: npm ci

      - name: Build and deploy
        working-directory: ./BlindWiki2
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          npm run predeploy
          npx gh-pages --dist dist --no-history --repo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" --user "GitHub Actions <actions@github.com>" --message "Deploy: ${GITHUB_SHA}"