name: Deploy to GitHub Pages

on:
  push:
    branches:
      - web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./BlindWiki2
        run: npm ci

      - name: Deploy to GitHub Pages
        working-directory: ./BlindWiki2
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          npm run deploy