name: Deploy to GitHub Pages

on:
  push:
    branches:
      - web

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change to BlindWiki2 directory
        run: cd BlindWiki2

      - name: Install dependencies
        working-directory: ./BlindWiki2
        run: npm ci

      - name: Build website
        working-directory: ./BlindWiki2
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: BlindWiki2/dist
          branch: gh-pages
          clean: true 